name: pulseops-airflow
version: '3.8'

networks:
  pulseops-net:
    external: true

services:
  # 1. PostgreSQL (Metadata)
  postgres-airflow:
    image: postgres:15
    container_name: airflow_db
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: airflow
    networks:
      - pulseops-net

  # 2. Redis - Message Broker cho Airflow Celery
  redis:
    image: redis:7.2-alpine
    container_name: airflow_redis
    ports:
      - "6379:6379"
    networks:
      - pulseops-net

  # 3. Airflow Init - Cài đặt database lần đầu
  airflow-init:
    image: apache/airflow:2.8.2
    container_name: airflow_init
    command: version
    environment: &airflow_env
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres-airflow/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres-airflow/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WEB_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WEB_PASSWORD}
      _PIP_ADDITIONAL_REQUIREMENTS: "confluent-kafka psycopg2-binary python-dotenv dbt-postgres"
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    depends_on:
      - postgres-airflow
      - redis
    networks:
      - pulseops-net

  # 4. Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.8.2
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8082:8080"
    environment: *airflow_env
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../dbt:/opt/airflow/dbt
      - ../src:/opt/airflow/src
    depends_on:
      - airflow-init
    networks:
      - pulseops-net

  # 5. Airflow Scheduler - Trái tim lên lịch chạy tác vụ
  airflow-scheduler:
    image: apache/airflow:2.8.2
    container_name: airflow_scheduler
    command: scheduler
    environment: *airflow_env
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../dbt:/opt/airflow/dbt
      - ../src:/opt/airflow/src
    depends_on:
      - airflow-init
    networks:
      - pulseops-net

  # 6. Airflow Worker - Công nhân thực thi lệnh
  airflow-worker:
    image: apache/airflow:2.8.2
    container_name: airflow_worker
    command: celery worker
    environment: *airflow_env
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../dbt:/opt/airflow/dbt
      - ../src:/opt/airflow/src
    depends_on:
      - airflow-init
    networks:
      - pulseops-net
