# Global default values
replicaCount: 1

image:
  repository: ghcr.io/kiemnguyenn/pulseops
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

# Default resource limits
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
